# Use DecapBridge PKCE auth (required)
backend:
  name: git-gateway
  repo: soundbyjek/portfolio
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/552c840e-aa32-431c-913f-fedbca47ce56/pkce
  auth_token_endpoint: /sites/552c840e-aa32-431c-913f-fedbca47ce56/token
  gateway_url: https://gateway.decapbridge.com

# Percorsi multimediali obbligatori per Decap CMS
media_folder: "static/images"
public_folder: "/images"

# Enable PKCE fields (optional, recommended)
auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

# See who did what (optional)
commit_messages:
  create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
  update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
  delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
  uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
  deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
  openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in Decap CMS (optional)
site_url: https://soundbyjek.github.io

collections:
  - name: "works"
    label: "Audio projects"
    folder: "content/works"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Project title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Highlight in Home Page?", name: "featured", widget: "boolean", default: false }
      - { label: "Category", name: "category", widget: "select", options: ["Game Audio", "Redesign", "Linear Film", "UI / Synth"] }
      - { label: "Thumbnail", name: "image", widget: "image", required: false }
      - { label: "Link Media Embed (YouTube/Soundcloud/Vimeo)", name: "media_url", widget: "string", required: false }
      - { label: "Software / Tech Stack", name: "tech_stack", widget: "list", default: ["Ardour", "FMOD"] }
      - { label: "Description & Breakdown", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Static Pages"
    files:
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Bio & Artistic Vision", name: "body", widget: "markdown" }
